# Use an official Node.js runtime as a parent image
FROM node:24-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application and test code
COPY src ./src
COPY tests ./tests

# Command to run the tester script
CMD ["node", "tests/tester.ts"]
